In [14]:
# PCA — Principal Component Analysis
# Réduire des données de haute dimension en gardant l'essentiel

# Simuler un dataset : 100 exemples, 3 features
np.random.seed(42)
X = np.random.randn(100, 3)

# Étape 1 : centrer les données (soustraire la moyenne)
X_centre = X - np.mean(X, axis=0)

# Étape 2 : calculer la matrice de covariance
cov_matrix = np.cov(X_centre.T)
print("Matrice de covariance :\n", cov_matrix)

# Étape 3 : valeurs et vecteurs propres de la covariance
valeurs, vecteurs = np.linalg.eig(cov_matrix)
print("\nValeurs propres :", valeurs)

# Étape 4 : variance expliquée par chaque composante
variance_expliquee = valeurs / np.sum(valeurs)
print("\nVariance expliquée :", variance_expliquee)
print("Variance cumulée :", np.cumsum(variance_expliquee))

# Étape 5 : projeter sur les 2 premières composantes
X_pca = X_centre @ vecteurs[:, :2]
print("\nShape original :", X.shape)
print("Shape après PCA :", X_pca.shape)

Matrice de covariance :
 [[ 0.68029352 -0.03927641 -0.1108006 ]
 [-0.03927641  0.9586369  -0.1348594 ]
 [-0.1108006  -0.1348594   1.23856849]]

Valeurs propres : [1.30567458 0.64493904 0.92688528]

Variance expliquée : [0.45375329 0.22413181 0.3221149 ]
Variance cumulée : [0.45375329 0.6778851  1.        ]

Shape original : (100, 3)
Shape après PCA : (100, 2)


In [11]:
a = np.arange(12)
print("Tableau original :", a)
print("Shape :", a.shape)

# Reshaper en matrice 3x4
b = a.reshape(3, 4)
print("\nReshaped (3x4) :\n", b)

# -1 = NumPy calcule automatiquement la dimension
c = a.reshape(2, -1)
print("\nReshaped (2, auto) :\n", c)
print("Shape :", c.shape)

# Aplatir en 1D
d = b.flatten()
print("\nFlatten :", d)

Tableau original : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape : (12,)

Reshaped (3x4) :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped (2, auto) :
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Shape : (2, 6)

Flatten : [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
# Valeurs propres et vecteurs propres
# Pour une matrice A : A·v = λ·v
# v = vecteur propre (ne change pas de direction)
# λ = valeur propre (facteur d'échelle)

A = np.array([[4, 2],
              [1, 3]])

valeurs_propres, vecteurs_propres = np.linalg.eig(A)

print("Matrice A :\n", A)
print("\nValeurs propres (λ) :", valeurs_propres)
print("\nVecteurs propres (v) :\n", vecteurs_propres)

# Vérification : A·v = λ·v
v0 = vecteurs_propres[:, 0]   # premier vecteur propre
λ0 = valeurs_propres[0]       # première valeur propre

print("\nVérification A·v0 :", A @ v0)
print("λ0·v0 :", λ0 * v0)

Matrice A :
 [[4 2]
 [1 3]]

Valeurs propres (λ) : [5. 2.]

Vecteurs propres (v) :
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

Vérification A·v0 : [4.47213595 2.23606798]
λ0·v0 : [4.47213595 2.23606798]


In [9]:
M = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

print("Matrice M :\n", M)

# Sélectionner une ligne
print("\nLigne 0 :", M[0])
print("Ligne 2 :", M[2])

# Sélectionner une colonne
print("\nColonne 1 :", M[:, 1])

# Sélectionner un sous-tableau (slicing)
print("\nLignes 0-1, colonnes 1-2 :\n", M[0:2, 1:3])

# Boolean indexing — sélectionner selon une condition
print("\nÉléments > 6 :", M[M > 6])

Matrice M :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Ligne 0 : [1 2 3 4]
Ligne 2 : [ 9 10 11 12]

Colonne 1 : [ 2  6 10]

Lignes 0-1, colonnes 1-2 :
 [[2 3]
 [6 7]]

Éléments > 6 : [ 7  8  9 10 11 12]


In [8]:
# Matrices spéciales

# Matrice de zéros — initialisation des poids d'un réseau de neurones
zeros = np.zeros((3, 4))
print("Zeros :\n", zeros)

# Matrice de uns
ones = np.ones((2, 3))
print("\nOnes :\n", ones)

# Matrice identité — très importante en algèbre linéaire
identite = np.eye(3)
print("\nIdentité :\n", identite)

# Matrice aléatoire — initialisation des poids en deep learning
aleatoire = np.random.randn(3, 3)
print("\nAléatoire (normale) :\n", aleatoire)

Zeros :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones :
 [[1. 1. 1.]
 [1. 1. 1.]]

Identité :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Aléatoire (normale) :
 [[ 0.18802008 -0.13552459  0.89421002]
 [ 1.42523467  0.67646018  0.90215839]
 [-0.36010776  0.47698566  0.43836248]]


In [3]:
import numpy as np

# Un vecteur = une liste de nombres
# En ML, chaque exemple de données est représenté comme un vecteur

v=np.array([1,2,3])
print("Vecteur :", v)
print("Type :", type(v))
print("Forme (shape) :", v.shape)
print("Dimension :", v.ndim)

Vecteur : [1 2 3]
Type : <class 'numpy.ndarray'>
Forme (shape) : (3,)
Dimension : 1


In [5]:
#Les Operations sur les vecteurs
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a :", a)
print("b :", b)
print("a + b :", a + b)
print("a * 2 :", a * 2)
print("a * b :", a * b)

# Produit scalaire (dot product) - tres utilisé en ML
dot = np.dot(a, b)
print("Prodiot scalaire a.b :", dot)

# Norme (longueur du vecteur)
norme = np.linalg.norm(a)
print("Norme de a :", norme)


a : [1 2 3]
b : [4 5 6]
a + b : [5 7 9]
a * 2 : [2 4 6]
a * b : [ 4 10 18]
Prodiot scalaire a.b : 32
Norme de a : 3.7416573867739413


In [6]:
# Une matrice = tableau de nombres à 2 dimensions
# En ML : un dataset entier est une matrice (lignes=exemples, colonnes=features)

M = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Matrice M :")
print(M)
print("Shape :", M.shape)   # (2 lignes, 3 colonnes)
print("Dimensions :", M.ndim)

# Accéder aux éléments
print("Ligne 0 :", M[0])
print("Élément ligne 1, colonne 2 :", M[1, 2])
print("Transposée :\n", M.T)

Matrice M :
[[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Dimensions : 2
Ligne 0 : [1 2 3]
Élément ligne 1, colonne 2 : 6
Transposée :
 [[1 4]
 [2 5]
 [3 6]]


In [7]:
# Multiplication matricielle
# Règle : A (m×n) @ B (n×p) = C (m×p)
# Les colonnes de A doivent égaler les lignes de B

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])   # shape (3, 2)

B = np.array([[7, 8, 9],
              [10, 11, 12]])  # shape (2, 3)

C = A @ B   # shape résultat : (3, 3)

print("A shape:", A.shape)
print("B shape:", B.shape)
print("A @ B =")
print(C)
print("C shape:", C.shape)

A shape: (3, 2)
B shape: (2, 3)
A @ B =
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
C shape: (3, 3)


In [ ]:
data = np.array([[85, 92, 78],
                 [90, 88, 95],
                 [70, 75, 80],
                 [95, 98, 92]])

print("Dataset :\n", data)
print("\nShape :", data.shape, "→ 4 exemples, 3 features")

# Statistiques globales
print("\nMoyenne globale :", np.mean(data))
print("Min :", np.min(data))
print("Max :", np.max(data))

# Statistiques par colonne (axis=0) → moyenne de chaque feature
print("\nMoyenne par feature (colonne) :", np.mean(data, axis=0))
print("Écart-type par feature :", np.std(data, axis=0))

# Statistiques par ligne (axis=1) → moyenne de chaque exemple
print("\nMoyenne par exemple (ligne) :", np.mean(data, axis=1))



Dataset :
 [[85 92 78]
 [90 88 95]
 [70 75 80]
 [95 98 92]]

Shape : (4, 3) → 4 exemples, 3 features

Moyenne globale : 86.5
Min : 70
Max : 98

Moyenne par feature (colonne) : [85.   88.25 86.25]
Écart-type par feature : [9.35414347 8.43726852 7.36121593]

Moyenne par exemple (ligne) : [85. 91. 75. 95.]
